services:
  app:
    image: gitlab.cloud.untad.ac.id:5050/untad/siakad/siakad-base
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    ports: 
      - 8080:80
    restart: unless-stopped
    depends_on: 
      - db
    container_name: siakad

  redis:
    image: redis
    volumes:
      - ./redis:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: always 
    ports:
      - '6379:6379'
    container_name: redis-siakad

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_DATABASE: siasfo2
      TZ: Asia/Makassar
    volumes:
      - ./db:/var/lib/mysql
    container_name: db-siakad
