version: "3.3" 
services:
  app:
    image: gitlab.cloud.untad.ac.id:5050/untad/siakad/siakad-base
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    #ports: 
    # - 8080:80
        #- 443:443
    restart: unless-stopped
    depends_on: 
      - db
    container_name: siakad
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-siakad.entrypoints=http"
      - "traefik.http.routers.admin-siakad.rule=Host(`admin-siakad2.untad.ac.id`)"
      - "traefik.http.middlewares.admin-siakad-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.admin-siakad.middlewares=admin-siakad-https-redirect"
      - "traefik.http.routers.admin-siakad-secure.entrypoints=https"
      - "traefik.http.routers.admin-siakad-secure.rule=Host(`admin-siakad2.untad.ac.id`)"
      - "traefik.http.routers.admin-siakad-secure.tls=true"
      - "traefik.http.routers.admin-siakad-secure.service=admin-siakad"
      - "traefik.http.services.admin-siakad.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
     - proxy

  redis:
    image: redis
    volumes:
      - ./redis:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: always 
    ports:
      - '6379:6379'
    container_name: redis-siakad

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_DATABASE: siasfo2
      TZ: Asia/Makassar
    volumes:
      - ./db:/var/lib/mysql
    container_name: db-siakad
    networks:
     - proxy

networks:
  proxy:
    external: true
